accessLog:
  filePath: /etc/traefik/access.log
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true
entryPoints:
  mc-java:
    address: ":25565"
  mc-bedrock:
    address: ":19132/udp"